### ISSUE TITLE
Menu not showing

### ISSUE THREAD

**Issue by brandodt** [xDreamms/EnsoulSharp#1]
[09-07-2020 07:24:13 - Warn]: (OnGameLoadUpdate) -> Catch An Error on OnGameLoad!
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: This menu already contains a component with the name targetBrand
   at EnsoulSharp.SDK.MenuUI.Menu.Add[T](T component)
   at Enceladus.DLL_BaseUlt.Helper.MenuHelper.AddMenuBool(Menu menu, String name, String displayName, Boolean value)
   at Enceladus.DLL_BaseUlt.Menu.MenuManager.LoadMenu()
   at Enceladus.DLL_BaseUlt.Core.BaseUlt.OnLoad()
   at Enceladus.DLL.Loader.Py6q7Xsz6HlLcCt8MA15()
   at Enceladus.DLL.Loader.GameEventOnOnGameLoad()
   at xDreamms.AIO.Program.h1CTv2VV8LXTWy1aBZW()
   at xDreamms.AIO.Program.YuMrCAlsjf()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at EnsoulSharp.SDK.GameEvent.OnGameLoadUpdate(EventArgs args)

**Comment by xDreamms** [comment]
.
